from __future__ import annotations

import hashlib
import json
from pathlib import Path
import subprocess
import sys
import tempfile
from typing import Any, Mapping


REPOSITORY_ROOT = Path(__file__).resolve().parents[3]
PLUGIN_SRC = REPOSITORY_ROOT / "plugins" / "torii-sumo" / "src"
if str(PLUGIN_SRC) not in sys.path:
    sys.path.insert(0, str(PLUGIN_SRC))

from torii_sumo.core.artifact_io import write_json_atomic  # noqa: E402
from torii_sumo.core.teacher_free_topology_workflow import (  # noqa: E402
    run_teacher_free_topology_workflow,
)


TOOLCHAIN_LOCK = (
    REPOSITORY_ROOT
    / "benchmarks"
    / "corridor_human_modeling_v1"
    / "toolchain.lock.json"
)
XS1_OSM = (
    REPOSITORY_ROOT
    / "examples"
    / "03_xs1_four_way_tls"
    / "input"
    / "xs1-89129156.osm.xml.gz"
)
XS2_OSM = (
    REPOSITORY_ROOT
    / "examples"
    / "04_xs2_three_way_tls"
    / "input"
    / "xs2-7009179660.osm.xml"
)
PAIRED_OFFSET_OSM = (
    REPOSITORY_ROOT
    / "tests"
    / "intersection"
    / "fixtures"
    / "paired_offset_shared_tls.osm.xml"
)
OUTPUT_ROOT = REPOSITORY_ROOT / "outputs" / "teacher-free-topology-v4"
TOPOLOGIES = {
    "preserve_split_shared_controller",
    "merge_physical_cell",
    "partial_internal_repair",
}
COMMON_GATE_KEYS = {
    "candidate_netconvert",
    "source_osm_immutable",
    "tls_ownership",
    "cell_movement_binding",
    "movement_semantics_exact",
    "target_connection_mode",
    "independent_conflict_safety",
    "outside_scope_exact_zero_delta",
    "sumo_load",
    "all_movement_routeability",
}


def main() -> int:
    _run(
        [
            sys.executable,
            "-m",
            "pytest",
            "tests/intersection/test_teacher_free_autodiscovery.py",
            "-q",
        ],
        label="focused teacher-free topology tests",
    )
    frozen_hashes = {
        str(path): _file_sha256(path)
        for path in (XS1_OSM, XS2_OSM, PAIRED_OFFSET_OSM, TOOLCHAIN_LOCK)
    }

    xs1 = _run_workflow(XS1_OSM, OUTPUT_ROOT / "xs1")
    _verify_xs1(xs1)

    xs2 = _run_workflow(XS2_OSM, OUTPUT_ROOT / "xs2", expect_blocked=True)
    _verify_xs2(xs2)

    paired = _run_workflow(
        PAIRED_OFFSET_OSM,
        OUTPUT_ROOT / "paired-offset",
    )
    _verify_paired_offset(paired)
    _require(
        xs1["producer"] == xs2["producer"] == paired["producer"],
        "Frozen scenes were not generated by one identical producer state",
        {
            "xs1": xs1["producer"],
            "xs2": xs2["producer"],
            "paired": paired["producer"],
        },
    )
    _verify_formal_producer(xs1["producer"])

    with tempfile.TemporaryDirectory(prefix="torii-topology-v4-repeat-") as temp:
        repeat = _run_workflow(XS1_OSM, Path(temp) / "xs1-repeat")
        _require(
            _determinism_fingerprint(xs1) == _determinism_fingerprint(repeat),
            "XS1 clean rerun changed the normalized experiment result",
            {
                "first": _determinism_fingerprint(xs1),
                "repeat": _determinism_fingerprint(repeat),
            },
        )

    _require(
        frozen_hashes
        == {
            str(path): _file_sha256(path)
            for path in (XS1_OSM, XS2_OSM, PAIRED_OFFSET_OSM, TOOLCHAIN_LOCK)
        },
        "A frozen input or toolchain lock changed during verification",
        frozen_hashes,
    )

    _run([sys.executable, "-m", "pytest", "-q"], label="full pytest suite")
    _run(
        [
            sys.executable,
            "-m",
            "ruff",
            "check",
            "plugins/torii-sumo/src",
            "plugins/torii-sumo/scripts",
            "tests",
        ],
        label="Ruff",
    )

    result = {
        "schema": "torii.teacher-free-topology-verification/v1",
        "status": "pass",
        "experiment": "teacher-free-topology-discrimination-v4",
        "xs1": _verification_summary(xs1),
        "xs2": {
            "status": xs2["status"],
            "candidate_written": xs2["candidate_written"],
            "contract_id": xs2["contract_id"],
            "terminal_stage": xs2["details"]["terminal_stage"],
        },
        "paired_offset_negative": _verification_summary(paired),
        "deterministic_clean_rerun": True,
        "frozen_input_hashes": frozen_hashes,
        "producer": xs1["producer"],
        "automatic_topology_selection": "blocked",
        "field_timing_reconstruction": "blocked",
        "automatic_promotion_gate": "blocked",
        "claim_boundary": (
            "This verifies machine construction and falsification behavior on "
            "three frozen small scenes. It does not identify real-world topology "
            "truth, field timing, or an automatically promotable repair class."
        ),
    }
    result_file = OUTPUT_ROOT / "verification.json"
    write_json_atomic(result_file, result, sort_keys=True)
    print(json.dumps({**result, "verification_file": str(result_file)}, indent=2))
    return 0


def _run_workflow(
    osm_file: Path,
    output_dir: Path,
    *,
    expect_blocked: bool = False,
) -> dict[str, Any]:
    result = run_teacher_free_topology_workflow(
        osm_file=osm_file,
        output_dir=output_dir,
        traffic_side="right",
        toolchain_lock_file=TOOLCHAIN_LOCK,
        timeout_seconds=180.0,
    )
    if not expect_blocked:
        _require(
            result["status"] == "review_ready",
            f"{osm_file.name} did not reach review_ready",
            result,
        )
    return result


def _verify_xs1(report: Mapping[str, Any]) -> None:
    variants = _variants_by_topology(report)
    _require(
        set(variants) == TOPOLOGIES,
        "XS1 did not materialize all three preregistered topology arms",
        variants,
    )
    _require(
        report["machine_decision"] == "blind_review_required"
        and report["machine_feasible_variant_count"] >= 2,
        "XS1 did not retain multiple feasible arms for blind review",
        report,
    )
    _require(
        report["scope_expansion_allowed"] is False,
        "XS1 workflow permitted scope expansion",
        report,
    )
    _require(
        report["blind_review"]["variant_count"]
        == report["machine_feasible_variant_count"],
        "XS1 blind package does not cover every feasible arm",
        report["blind_review"],
    )
    for variant in variants.values():
        _verify_variant_common(variant, expected_producer=report["producer"])
        _require(
            set(variant["gates"]) == COMMON_GATE_KEYS,
            "A topology arm was not evaluated with the common frozen gate set",
            variant,
        )
        _require(
            variant["cell_movement_binding"]["movement_count"] == 12,
            "XS1 topology arm did not expose all twelve stable movements",
            variant,
        )
        _require(
            variant["all_movement_routeability"]["status"] == "pass"
            and variant["all_movement_routeability"]["arrived_vehicle_count"]
            == 12,
            "XS1 topology arm did not complete all movement routes",
            variant,
        )
    split = variants["preserve_split_shared_controller"]
    _require(
        not split["machine_feasible"]
        and split["gates"]["independent_conflict_safety"] == "review",
        "XS1 split arm was not fail-closed on its independent conflict result",
        split,
    )
    for topology in ("merge_physical_cell", "partial_internal_repair"):
        _require(
            variants[topology]["machine_feasible"]
            and all(value == "pass" for value in variants[topology]["gates"].values()),
            f"XS1 {topology} did not pass every machine gate",
            variants[topology],
        )
    _verify_contract_policy(Path(str(report["artifacts"]["topology_contract"])))
    _verify_manifest_closure(
        Path(str(report["manifest_file"])),
        expected_producer=report["producer"],
    )


def _verify_xs2(report: Mapping[str, Any]) -> None:
    _require(
        report["status"] == "blocked"
        and report["candidate_written"] is False
        and report["details"]["terminal_stage"] == "pre_materialization",
        "XS2 did not fail closed before source or candidate materialization",
        report,
    )
    _require(
        report["scope_expansion_allowed"] is False,
        "XS2 blocker permitted scope expansion",
        report,
    )
    _require(
        any(
            "movement_semantic_variants_disagree"
            in arm["pre_materialization_blockers"]
            for assessment in report["candidate_assessments"]
            for arm in assessment["topology_arms"]
        ),
        "XS2 did not retain its movement semantic disagreement",
        report,
    )
    output = Path(str(report["summary_file"])).parent
    _require(
        not (output / "source.net.xml").exists()
        and not (output / "variants").exists(),
        "XS2 wrote network candidates despite its pre-materialization blocker",
        {"output": str(output)},
    )
    _verify_manifest_closure(
        Path(str(report["manifest_file"])),
        expected_producer=report["producer"],
    )


def _verify_paired_offset(report: Mapping[str, Any]) -> None:
    contract = _read_json(Path(str(report["artifacts"]["topology_contract"])))
    assessment = next(
        item
        for item in contract["candidate_assessments"]
        if item["classification"]["kind"] == "vehicle_intersection"
    )
    evidence = assessment["topology_evidence"]
    arms = {
        item["topology_hypothesis"]: item for item in assessment["topology_arms"]
    }
    _require(
        evidence["signal_anchor_count"] == 4
        and evidence["branch_node_count"] == 2
        and bool(evidence["storage_capable_connectors"]),
        "Paired/offset negative does not preserve its falsifying evidence",
        evidence,
    )
    _require(
        arms["merge_physical_cell"]["pre_materialization_status"] == "blocked"
        and {
            "merge_requires_exactly_one_vehicle_conflict_center",
            "storage_capable_connector_falsifies_single_cell_merge",
        }.issubset(
            set(
                arms["merge_physical_cell"]["pre_materialization_blockers"]
            )
        ),
        "Four signal heads incorrectly authorized a physical merge",
        arms["merge_physical_cell"],
    )
    _require(
        report["machine_decision"]
        == "suggest_single_machine_feasible_arm_for_human_review",
        "Paired/offset negative did not remain a review-only suggestion",
        report,
    )
    _require(
        report["scope_expansion_allowed"] is False,
        "Paired/offset workflow permitted scope expansion",
        report,
    )
    variants = _variants_by_topology(report)
    _require(
        set(variants) == {"preserve_split_shared_controller"}
        and variants["preserve_split_shared_controller"]["machine_feasible"],
        "Paired/offset scene did not preserve the split/shared-controller arm",
        variants,
    )
    split = variants["preserve_split_shared_controller"]
    _verify_variant_common(split, expected_producer=report["producer"])
    _require(
        all(value == "pass" for value in split["gates"].values())
        and split["cell_movement_binding"]["movement_count"] == 12
        and split["all_movement_routeability"]["arrived_vehicle_count"] == 12,
        "Paired/offset split arm did not close every common machine gate",
        split,
    )
    output = Path(str(report["summary_file"])).parent
    _require(
        not (output / "variants" / "hm").exists(),
        "Paired/offset merge artifact was written after preflight falsification",
        {"output": str(output)},
    )
    _verify_contract_policy(Path(str(report["artifacts"]["topology_contract"])))
    _verify_manifest_closure(
        Path(str(report["manifest_file"])),
        expected_producer=report["producer"],
    )


def _verify_variant_common(
    variant: Mapping[str, Any],
    *,
    expected_producer: Mapping[str, Any],
) -> None:
    _require(
        variant["automatic_topology_selection"] is False
        and variant["automatic_promotion_gate"] == "blocked"
        and variant["field_timing_reconstruction"] is False
        and variant["source_mutation"] is False,
        "A topology variant crossed a forbidden authority boundary",
        variant,
    )
    _require(
        variant["producer"] == expected_producer,
        "Topology variant producer identity differs from its workflow",
        variant,
    )
    for role in (
        "node_patch",
        "build_report",
        "tls_ownership",
        "cell_movement_binding",
        "exact_audit_manifest",
        "rollback",
        "review_overlay",
    ):
        _require(
            Path(str(variant["artifacts"][role])).is_file(),
            f"Topology variant is missing {role}",
            variant,
        )
    rollback = _read_json(Path(str(variant["artifacts"]["rollback"])))
    _require(
        rollback["status"] == "available"
        and rollback["inverse_operation"]["source_mutation"] is False
        and rollback["automatic_promotion_gate"] == "blocked",
        "Topology variant rollback is incomplete",
        rollback,
    )
    exact_dir = Path(str(variant["artifacts"]["exact_audit_manifest"])).parent
    exact_files = list(exact_dir.glob("*.exact-diff.json"))
    _require(
        len(exact_files) == 1,
        "Topology variant does not have one exact semantic delta",
        {"exact_dir": str(exact_dir)},
    )
    exact = _read_json(exact_files[0])
    _require(
        exact["status"] == "pass"
        and not exact["outside_scope_delta_ids"]
        and not exact["outside_scope_added_finding_ids"],
        "Topology variant introduced an outside-scope semantic delta",
        exact,
    )
    routeability = _read_json(
        Path(str(variant["all_movement_routeability"]["report_file"]))
    )
    _require(
        routeability["status"] == "pass"
        and all(routeability["checks"].values())
        and routeability["inspection"]["summary"]["collisions"] == 0
        and routeability["inspection"]["summary"]["teleports"] == 0,
        "Topology variant movement smoke is not collision-clean and complete",
        routeability,
    )
    _verify_manifest_closure(
        Path(str(variant["manifest_file"])),
        expected_producer=expected_producer,
    )


def _verify_contract_policy(path: Path) -> None:
    contract = _read_json(path)
    forbidden = set(contract["forbidden_inputs"])
    _require(
        {
            "teacher_network",
            "teacher_coordinates",
            "manual_seed_node",
            "manual_scope",
            "expected_topology",
            "expected_approach_count",
            "expected_movement_count",
            "expected_topology_winner",
            "reviewed_junction_id",
            "field_signal_timing",
        }.issubset(forbidden),
        "Topology contract does not explicitly forbid benchmark answers",
        contract,
    )
    _require(
        contract["automatic_topology_selection"] is False
        and contract["automatic_promotion_gate"] == "blocked"
        and contract["field_timing_reconstruction"] is False
        and contract["manual_scope_input"] is False
        and contract["scope_expansion_allowed"] is False,
        "Topology contract grants authority outside the v4 experiment",
        contract,
    )


def _verify_manifest_closure(
    path: Path,
    *,
    expected_producer: Mapping[str, Any],
) -> None:
    manifest = _read_json(path)
    _require(
        manifest["producer"] == expected_producer,
        "Artifact manifest does not bind the workflow producer",
        manifest,
    )
    mismatches = []
    for record in [*manifest.get("inputs", ()), *manifest.get("artifacts", ())]:
        artifact = Path(str(record["path"]))
        actual = _file_sha256(artifact) if artifact.is_file() else None
        if actual != record.get("sha256"):
            mismatches.append(
                {
                    "path": str(artifact),
                    "expected_sha256": record.get("sha256"),
                    "actual_sha256": actual,
                }
            )
    _require(not mismatches, "Artifact manifest hash closure failed", mismatches)


def _determinism_fingerprint(report: Mapping[str, Any]) -> dict[str, Any]:
    variants = _variants_by_topology(report)
    return {
        "status": report["status"],
        "machine_decision": report["machine_decision"],
        "discovery_id": report["discovery_id"],
        "contract_id": report["contract_id"],
        "topology_evidence_id": report["topology_evidence_id"],
        "candidate_dag_id": report["candidate_dag_id"],
        "producer_state_id": report["producer"]["producer_state_id"],
        "variants": {
            topology: {
                "candidate_plan_id": item["candidate_plan_id"],
                "candidate_dag_node_id": item["candidate_dag_node_id"],
                "normalized_sha256": item["candidate_net"]["normalized_sha256"],
                "binding_id": item["binding_id"],
                "gates": item["gates"],
                "machine_feasible": item["machine_feasible"],
            }
            for topology, item in sorted(variants.items())
        },
    }


def _verification_summary(report: Mapping[str, Any]) -> dict[str, Any]:
    return {
        "status": report["status"],
        "machine_decision": report["machine_decision"],
        "contract_id": report["contract_id"],
        "candidate_dag_id": report["candidate_dag_id"],
        "materialized_variant_count": report["materialized_variant_count"],
        "machine_feasible_variant_count": report[
            "machine_feasible_variant_count"
        ],
        "variants": {
            topology: {
                "status": variant["status"],
                "machine_feasible": variant["machine_feasible"],
                "normalized_sha256": variant["candidate_net"][
                    "normalized_sha256"
                ],
                "movement_count": variant["cell_movement_binding"][
                    "movement_count"
                ],
                "gates": variant["gates"],
            }
            for topology, variant in sorted(_variants_by_topology(report).items())
        },
        "manifest_file": report["manifest_file"],
        "producer_state_id": report["producer"]["producer_state_id"],
    }


def _verify_formal_producer(producer: Mapping[str, Any]) -> None:
    _require(
        producer["schema"] == "torii.code-producer-state/v1"
        and producer["working_tree_clean"] is True
        and producer["untracked_file_count"] == 0
        and _is_lower_hex(str(producer["revision"]), length=40)
        and _is_lower_hex(str(producer["tree_revision"]), length=40)
        and _is_lower_hex(str(producer["worktree_state_sha256"]), length=64),
        "Authoritative verification requires one clean, hash-bound Git producer",
        producer,
    )


def _is_lower_hex(value: str, *, length: int) -> bool:
    return len(value) == length and all(character in "0123456789abcdef" for character in value)


def _variants_by_topology(
    report: Mapping[str, Any],
) -> dict[str, Mapping[str, Any]]:
    return {
        str(item["topology_hypothesis"]): item
        for item in report.get("variants", ())
    }


def _read_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def _file_sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _run(command: list[str], *, label: str) -> None:
    print(f"\n== {label} ==", flush=True)
    completed = subprocess.run(
        command,
        cwd=REPOSITORY_ROOT,
        check=False,
    )
    if completed.returncode != 0:
        raise SystemExit(completed.returncode)


def _require(condition: bool, message: str, evidence: object) -> None:
    if condition:
        return
    print(message, file=sys.stderr)
    print(json.dumps(evidence, indent=2, default=str), file=sys.stderr)
    raise SystemExit(1)


if __name__ == "__main__":
    raise SystemExit(main())
