"""Compatibility imports for the junction rebuild domain modules."""

from .junction_rebuild.artifacts import (
    _command_report as _command_report,
    _failure as _failure,
    _queue_candidate_dir as _queue_candidate_dir,
    _safe_stage_name as _safe_stage_name,
    _stage_file as _stage_file,
    _variant_exception_report as _variant_exception_report,
    _write_teacher_guided_report as _write_teacher_guided_report,
)
from .junction_rebuild.boundary_restore import (
    _append_edge_lanes_to_destination_junction as _append_edge_lanes_to_destination_junction,
    _preserve_boundary_operational_attributes as _preserve_boundary_operational_attributes,
    _preserve_mapped_boundary_geometry as _preserve_mapped_boundary_geometry,
    _remove_edge_lanes_from_destination_junction as _remove_edge_lanes_from_destination_junction,
    _restore_existing_edge_geometry as _restore_existing_edge_geometry,
    _restore_external_boundary_connections as _restore_external_boundary_connections,
    _restore_joined_split_edge_geometry as _restore_joined_split_edge_geometry,
)
from .junction_rebuild.cases import (
    _attach_junction_pattern_delta as _attach_junction_pattern_delta,
    _candidate_junction_id_candidates as _candidate_junction_id_candidates,
    _junction_pattern_delta_keys as _junction_pattern_delta_keys,
    _netedit_review_actions as _netedit_review_actions,
    _same_id_pattern_cases as _same_id_pattern_cases,
    _same_id_tls_matches_teacher as _same_id_tls_matches_teacher,
    _same_id_tls_mismatch_cases as _same_id_tls_mismatch_cases,
    _teacher_approach_edge_ids as _teacher_approach_edge_ids,
    _teacher_guided_case_sort_key as _teacher_guided_case_sort_key,
    _teacher_junction_has_tls as _teacher_junction_has_tls,
    _teacher_pattern_metric_is_positive as _teacher_pattern_metric_is_positive,
    _teacher_template_count_for_case as _teacher_template_count_for_case,
    _tls_repair_actions as _tls_repair_actions,
    _tls_repair_candidates as _tls_repair_candidates,
    _topology_fragmented_non_tls_cases as _topology_fragmented_non_tls_cases,
    _topology_fragmented_tls_cases as _topology_fragmented_tls_cases,
    _turnaround_only_lane_cases as _turnaround_only_lane_cases,
    _turnaround_only_lane_gaps as _turnaround_only_lane_gaps,
)
from .junction_rebuild.connections import (
    build_tls_connection_repair_variant as build_tls_connection_repair_variant,
    write_teacher_connection_plan as write_teacher_connection_plan,
    write_teacher_vehicle_connection_attrs_net as write_teacher_vehicle_connection_attrs_net,
)
from .junction_rebuild.edge_mapping import (
    _approach_endpoint_rebuild_plan as _approach_endpoint_rebuild_plan,
    _augment_candidate_edge_map_from_tls_approach_pairs as _augment_candidate_edge_map_from_tls_approach_pairs,
    _candidate_edge_by_exact_or_unsplit_id as _candidate_edge_by_exact_or_unsplit_id,
    _candidate_nodes_from_exact_teacher_approach_edges as _candidate_nodes_from_exact_teacher_approach_edges,
    _case_boundary_edge_map as _case_boundary_edge_map,
    _copyable_missing_teacher_edge_ids as _copyable_missing_teacher_edge_ids,
    _drop_endpoint_mismatched_edge_map_entries as _drop_endpoint_mismatched_edge_map_entries,
    _edge_map_from_approach_endpoint_rebuild_plan as _edge_map_from_approach_endpoint_rebuild_plan,
    _load_geometry_anchor_edge_ids as _load_geometry_anchor_edge_ids,
    _missing_teacher_edge_endpoint_ids as _missing_teacher_edge_endpoint_ids,
    _missing_teacher_movement_plan as _missing_teacher_movement_plan,
    _needed_unmapped_teacher_boundary_edges as _needed_unmapped_teacher_boundary_edges,
    _prefer_existing_exact_edge_ids as _prefer_existing_exact_edge_ids,
    _same_family_continuation_edge_map as _same_family_continuation_edge_map,
    _stale_case_edge_map_entries as _stale_case_edge_map_entries,
    _teacher_boundary_edge_ids_touching_internal_subgraph as _teacher_boundary_edge_ids_touching_internal_subgraph,
    _teacher_boundary_edge_needs_replay as _teacher_boundary_edge_needs_replay,
    _teacher_candidate_edge_map as _teacher_candidate_edge_map,
    _valid_edge_map as _valid_edge_map,
)
from .junction_rebuild.geometry import (
    _blend_geometry_anchor_at_endpoint as _blend_geometry_anchor_at_endpoint,
    _blend_geometry_anchor_at_target as _blend_geometry_anchor_at_target,
    _clone_transformed_boundary_junction as _clone_transformed_boundary_junction,
    _clone_transformed_junction as _clone_transformed_junction,
    _convex_hull as _convex_hull,
    _edge_geometry_matches_current_junctions as _edge_geometry_matches_current_junctions,
    _edge_lane_shapes as _edge_lane_shapes,
    _edge_touches_context as _edge_touches_context,
    _estimate_linear_lane_transition_shape as _estimate_linear_lane_transition_shape,
    _expand_junction_shape_to_approach_endpoints as _expand_junction_shape_to_approach_endpoints,
    _format_xy as _format_xy,
    _join_shape_text as _join_shape_text,
    _joined_lane_length as _joined_lane_length,
    _junction_within_radius as _junction_within_radius,
    _junction_xy as _junction_xy,
    _load_geometry_anchor_edges as _load_geometry_anchor_edges,
    _mapped_connection_attrs as _mapped_connection_attrs,
    _mapped_junction_attrs as _mapped_junction_attrs,
    _mapped_spatial_attrs as _mapped_spatial_attrs,
    _model_junction_origin as _model_junction_origin,
    _model_shape_delta as _model_shape_delta,
    _polygon_area as _polygon_area,
    _polyline_length as _polyline_length,
    _primary_edge_shape as _primary_edge_shape,
    _relative_shape as _relative_shape,
    _shape_endpoints as _shape_endpoints,
    _shape_points as _shape_points,
    _teacher_to_candidate_delta as _teacher_to_candidate_delta,
    _translate_shape as _translate_shape,
    _translated_edge_lane_shapes as _translated_edge_lane_shapes,
    _translated_lane_attrs as _translated_lane_attrs,
    _warp_anchor_shape_to_teacher_endpoint as _warp_anchor_shape_to_teacher_endpoint,
)
from .junction_rebuild.lane_inputs import (
    write_missing_edge_type_patch as write_missing_edge_type_patch,
    write_teacher_endpoint_patch_nodes as write_teacher_endpoint_patch_nodes,
    write_teacher_lane_patch_edges as write_teacher_lane_patch_edges,
)
from .junction_rebuild.network import (
    GEOMETRY_RESTORE_LANE_ATTRS as GEOMETRY_RESTORE_LANE_ATTRS,
    ROAD_CONTINUITY_COUNT_FIELDS as ROAD_CONTINUITY_COUNT_FIELDS,
    ROAD_CONTINUITY_FAILURE_FIELDS as ROAD_CONTINUITY_FAILURE_FIELDS,
    TLS_CONNECTION_REPAIR_ATTRS as TLS_CONNECTION_REPAIR_ATTRS,
    TURNAROUND_DIR as TURNAROUND_DIR,
    _approach_edges as _approach_edges,
    _approaches as _approaches,
    _candidate_lane_counts as _candidate_lane_counts,
    _connection_edges_are_adjacent as _connection_edges_are_adjacent,
    _connection_key as _connection_key,
    _connection_key_record as _connection_key_record,
    _connection_lane_indices_valid as _connection_lane_indices_valid,
    _connection_link_indices as _connection_link_indices,
    _connection_touches_any_edge as _connection_touches_any_edge,
    _connection_touches_walkingarea_internal as _connection_touches_walkingarea_internal,
    _controlled_tls_connection_count as _controlled_tls_connection_count,
    _dict_mismatch_count as _dict_mismatch_count,
    _edge_drop_requires_review as _edge_drop_requires_review,
    _edge_family_id as _edge_family_id,
    _edge_file_lane_counts as _edge_file_lane_counts,
    _edge_is_pedestrian_only as _edge_is_pedestrian_only,
    _edge_is_vehicle_continuation_candidate as _edge_is_vehicle_continuation_candidate,
    _edge_lane_count as _edge_lane_count,
    _edge_type_signature as _edge_type_signature,
    _first_junction_index as _first_junction_index,
    _int_count as _int_count,
    _is_turnaround_connection as _is_turnaround_connection,
    _lanes_by_index as _lanes_by_index,
    _map_connection_endpoint as _map_connection_endpoint,
    _map_internal_ref as _map_internal_ref,
    _map_lane_ref as _map_lane_ref,
    _mapped_internal_ref as _mapped_internal_ref,
    _net_junction_ids as _net_junction_ids,
    _net_lane_counts as _net_lane_counts,
    _opposite_direction_edge_id as _opposite_direction_edge_id,
    _plain_crossing_node_id as _plain_crossing_node_id,
    _plain_edge_endpoints as _plain_edge_endpoints,
    _real_junction_ids as _real_junction_ids,
    _report_used_unrestored_normalized_replay as _report_used_unrestored_normalized_replay,
    _root_vehicle_outgoing_by_lane as _root_vehicle_outgoing_by_lane,
    _should_emit as _should_emit,
    _signed_edge_family_id as _signed_edge_family_id,
    _split as _split,
    _stable_digest as _stable_digest,
    _string_list as _string_list,
    _target_internal_replay_input_file as _target_internal_replay_input_file,
    _touches_other_internal_owner as _touches_other_internal_owner,
    _touches_target_internal_owner as _touches_target_internal_owner,
    _touches_target_internal_subgraph as _touches_target_internal_subgraph,
    _touches_target_replay_scope as _touches_target_replay_scope,
    _unique_connections_by_key as _unique_connections_by_key,
    _vehicle_outgoing_by_lane as _vehicle_outgoing_by_lane,
    _via_lane_edge_id as _via_lane_edge_id,
    _write_connections as _write_connections,
)
from .junction_rebuild.parity import (
    _blocking_removed_stale_boundary_connection_count as _blocking_removed_stale_boundary_connection_count,
    _blocking_removed_stale_connection_count as _blocking_removed_stale_connection_count,
    _compare_teacher_models as _compare_teacher_models,
    _final_composite_parity_gate as _final_composite_parity_gate,
    _final_context_parity_gate as _final_context_parity_gate,
    _hybrid_osm_approach_authority_policy as _hybrid_osm_approach_authority_policy,
    _pedestrian_crossing_delta_count as _pedestrian_crossing_delta_count,
    _road_continuity_probe_summary as _road_continuity_probe_summary,
    _semantic_layer_for_field as _semantic_layer_for_field,
    _semantic_layer_gates as _semantic_layer_gates,
    _teacher_guided_semantics_gate as _teacher_guided_semantics_gate,
    _teacher_parity_summary as _teacher_parity_summary,
)
from .junction_rebuild.pedestrians import (
    _apply_teacher_pedestrian_internal_geometry as _apply_teacher_pedestrian_internal_geometry,
    _copy_teacher_walkingareas as _copy_teacher_walkingareas,
    _map_teacher_pedestrian_endpoint as _map_teacher_pedestrian_endpoint,
    _pedestrian_tl_pairs_from_connections as _pedestrian_tl_pairs_from_connections,
    _pedestrian_tl_pairs_from_records as _pedestrian_tl_pairs_from_records,
    _touches_target_pedestrian_ring as _touches_target_pedestrian_ring,
    restore_scoped_pedestrian_internal_semantics_after_normalize as restore_scoped_pedestrian_internal_semantics_after_normalize,
    write_teacher_pedestrian_ring_net as write_teacher_pedestrian_ring_net,
)
from .junction_rebuild.planning import (
    _accepted_target_internal_replay_entry as _accepted_target_internal_replay_entry,
    _candidate_requests_target_internal_replay as _candidate_requests_target_internal_replay,
    _expanded_scope_followup_candidate_for_unsafe_internal_replay as _expanded_scope_followup_candidate_for_unsafe_internal_replay,
    _expanded_scope_skip_entry as _expanded_scope_skip_entry,
    _teacher_guided_repair_candidate as _teacher_guided_repair_candidate,
    build_rebuild_candidate as build_rebuild_candidate,
)
from .junction_rebuild.replay_plans import (
    build_scoped_teacher_tls_cell_replay_plan as build_scoped_teacher_tls_cell_replay_plan,
    build_shared_teacher_tls_controller_replay_plan as build_shared_teacher_tls_controller_replay_plan,
)
from .junction_rebuild.restoration import (
    _restore_non_target_internal_artifacts as _restore_non_target_internal_artifacts,
    _restore_replayed_geometry_attrs as _restore_replayed_geometry_attrs,
    restore_off_scope_netconvert_artifacts as restore_off_scope_netconvert_artifacts,
)
from .junction_rebuild.scope import (
    _conservative_join_node_ids as _conservative_join_node_ids,
    _context_count_delta as _context_count_delta,
    _endpoint_rewrite_old_endpoint_ids as _endpoint_rewrite_old_endpoint_ids,
    _endpoint_rewrites as _endpoint_rewrites,
    _expanded_rebuild_scope as _expanded_rebuild_scope,
    _join_internal_self_loop_drop_has_witness as _join_internal_self_loop_drop_has_witness,
    _join_patch_endpoint_rewrites as _join_patch_endpoint_rewrites,
    _join_patch_joined_node_ids as _join_patch_joined_node_ids,
    _joined_endpoint_self_loop_edge_ids as _joined_endpoint_self_loop_edge_ids,
    _joined_source_node_ids as _joined_source_node_ids,
    _load_teacher_join_groups_by_cluster as _load_teacher_join_groups_by_cluster,
    _local_junction_context_summary as _local_junction_context_summary,
    _normalize_joined_junction_ids as _normalize_joined_junction_ids,
    _split_cluster_member_residuals as _split_cluster_member_residuals,
    _sumo_cluster_member_ids as _sumo_cluster_member_ids,
    _sumo_joined_cluster_id as _sumo_joined_cluster_id,
)
from .junction_rebuild.scope_inputs import (
    _write_joined_endpoint_connection_file as _write_joined_endpoint_connection_file,
    _write_joined_endpoint_edge_file as _write_joined_endpoint_edge_file,
    _write_replay_node_file as _write_replay_node_file,
    write_expanded_scope_plain_inputs as write_expanded_scope_plain_inputs,
)
from .junction_rebuild.signatures import (
    _approach_edge_signature as _approach_edge_signature,
    _approach_edge_signatures as _approach_edge_signatures,
    _approach_endpoint_signatures as _approach_endpoint_signatures,
    _controlled_link_count as _controlled_link_count,
    _controlled_link_index_stats as _controlled_link_index_stats,
    _controlled_link_signature_group as _controlled_link_signature_group,
    _controlled_link_signatures as _controlled_link_signatures,
    _controlled_pedestrian_link_signatures as _controlled_pedestrian_link_signatures,
    _controlled_vehicle_link_signatures as _controlled_vehicle_link_signatures,
    _crossing_geometry_signatures as _crossing_geometry_signatures,
    _crossing_signatures as _crossing_signatures,
    _internal_connection_signatures as _internal_connection_signatures,
    _internal_edge_signature as _internal_edge_signature,
    _internal_edge_signatures as _internal_edge_signatures,
    _internal_junction_signatures as _internal_junction_signatures,
    _junction_signature as _junction_signature,
    _lane_length_signature as _lane_length_signature,
    _mapped_endpoint as _mapped_endpoint,
    _mapped_junction_ref as _mapped_junction_ref,
    _mapped_lane_ref as _mapped_lane_ref,
    _mapped_lane_refs as _mapped_lane_refs,
    _model_tls_id as _model_tls_id,
    _request_signatures as _request_signatures,
    _tl_phase_signatures as _tl_phase_signatures,
    _uncontrolled_pedestrian_connection_signatures as _uncontrolled_pedestrian_connection_signatures,
    _vehicle_connection_signature as _vehicle_connection_signature,
    _walking_area_signatures as _walking_area_signatures,
)
from .junction_rebuild.tls import (
    _add_green_phases_for_links as _add_green_phases_for_links,
    _capacity_gap_records as _capacity_gap_records,
    _connection_link_indices_fit as _connection_link_indices_fit,
    _connection_max_link_index as _connection_max_link_index,
    _copy_referenced_tllogics as _copy_referenced_tllogics,
    _demote_teacher_absent_context_tls as _demote_teacher_absent_context_tls,
    _pad_tllogic_state_lengths as _pad_tllogic_state_lengths,
    _phase_has_green_for_index as _phase_has_green_for_index,
    _record_linkindex_capacity_gap as _record_linkindex_capacity_gap,
    _remove_teacher_non_tls_tllogics as _remove_teacher_non_tls_tllogics,
    _restore_false_traffic_light_junction_types as _restore_false_traffic_light_junction_types,
    _tl_logic_insert_index as _tl_logic_insert_index,
    _tllogic_min_state_length_by_id as _tllogic_min_state_length_by_id,
    restore_teacher_tls_connection_semantics_after_normalize as restore_teacher_tls_connection_semantics_after_normalize,
    write_teacher_tllogic_net as write_teacher_tllogic_net,
)
